// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/get-solana-network-stats.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
var RPC_ENDPOINTS = [
  "https://api.mainnet-beta.solana.com",
  "https://solana-rpc.publicnode.com"
];
async function rpc(method, params = []) {
  let lastErr;
  for (const url of RPC_ENDPOINTS) {
    try {
      const r = await fetch(url, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ jsonrpc: "2.0", id: 1, method, params })
      });
      if (!r.ok) throw new Error(`${url} ${r.status}`);
      const j = await r.json();
      if (j.error) throw new Error(j.error.message ?? "rpc error");
      return j.result;
    } catch (e) {
      lastErr = e;
    }
  }
  throw lastErr ?? new Error("all rpc endpoints failed");
}
var get_solana_network_stats_default = defineTool({
  name: "get_solana_network_stats",
  title: "Get Solana network stats",
  description: "Return live Solana mainnet network stats: current epoch, slot, block height, and recent transactions-per-second sampled from a validator.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: false, openWorldHint: true },
  handler: async () => {
    try {
      const [epoch, samples] = await Promise.all([
        rpc("getEpochInfo"),
        rpc("getRecentPerformanceSamples", [1])
      ]);
      const sample = Array.isArray(samples) && samples[0] ? samples[0] : null;
      const tps = sample && sample.samplePeriodSecs ? Math.round(sample.numTransactions / sample.samplePeriodSecs) : null;
      const payload = {
        epoch: epoch?.epoch ?? null,
        slot: epoch?.absoluteSlot ?? null,
        blockHeight: epoch?.blockHeight ?? null,
        slotsInEpoch: epoch?.slotsInEpoch ?? null,
        slotIndex: epoch?.slotIndex ?? null,
        epochProgressPct: epoch?.slotsInEpoch && epoch?.slotIndex != null ? Number((epoch.slotIndex / epoch.slotsInEpoch * 100).toFixed(2)) : null,
        tps
      };
      return {
        content: [{ type: "text", text: JSON.stringify(payload, null, 2) }],
        structuredContent: payload
      };
    } catch (e) {
      return {
        content: [{ type: "text", text: `Failed to fetch Solana network stats: ${String(e.message ?? e)}` }],
        isError: true
      };
    }
  }
});

// src/lib/mcp/tools/get-protocol-revenue.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^3.25.76";
var get_protocol_revenue_default = defineTool2({
  name: "get_protocol_revenue",
  title: "Get top protocol revenue (Solana)",
  description: "Return top Solana protocols ranked by 24h revenue and fees from DeFiLlama's public API. Useful for identifying which protocols are earning the most.",
  inputSchema: {
    limit: z.number().int().min(1).max(50).default(10).describe("Number of protocols to return (1-50).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: true },
  handler: async ({ limit }) => {
    try {
      const [revRes, feeRes] = await Promise.all([
        fetch("https://api.llama.fi/overview/fees?dataType=dailyRevenue"),
        fetch("https://api.llama.fi/overview/fees?dataType=dailyFees")
      ]);
      if (!revRes.ok || !feeRes.ok) throw new Error(`llama ${revRes.status}/${feeRes.status}`);
      const rev = await revRes.json();
      const fees = await feeRes.json();
      const feeMap = /* @__PURE__ */ new Map();
      for (const p of fees.protocols ?? []) {
        if (p.chains?.includes("Solana")) feeMap.set(p.name, p.total24h ?? 0);
      }
      const rows = (rev.protocols ?? []).filter((p) => p.chains?.includes("Solana")).map((p) => ({
        name: p.name,
        category: p.category,
        dailyRevenue: p.total24h ?? 0,
        dailyFees: feeMap.get(p.name) ?? 0,
        change24h: p.change_1d ?? null
      })).sort((a, b) => b.dailyRevenue - a.dailyRevenue).slice(0, limit);
      const total = rows.reduce((s, r) => s + r.dailyRevenue, 0);
      const payload = { totalDailyRevenueUsd: total, count: rows.length, protocols: rows };
      return {
        content: [{ type: "text", text: JSON.stringify(payload, null, 2) }],
        structuredContent: payload
      };
    } catch (e) {
      return {
        content: [{ type: "text", text: `Failed to fetch protocol revenue: ${String(e.message ?? e)}` }],
        isError: true
      };
    }
  }
});

// src/lib/mcp/tools/get-token-price.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z2 } from "npm:zod@^3.25.76";
var get_token_price_default = defineTool3({
  name: "get_token_price",
  title: "Get Solana token price",
  description: "Look up the current USD price and 24h change for a Solana SPL token by mint address, via Jupiter's public price API.",
  inputSchema: {
    mint: z2.string().min(32).max(64).describe("Solana SPL token mint address (base58).")
  },
  annotations: { readOnlyHint: true, idempotentHint: false, openWorldHint: true },
  handler: async ({ mint }) => {
    try {
      const r = await fetch(`https://api.jup.ag/price/v2?ids=${encodeURIComponent(mint)}`);
      if (!r.ok) throw new Error(`jup ${r.status}`);
      const j = await r.json();
      const entry = j?.data?.[mint];
      if (!entry) {
        return {
          content: [{ type: "text", text: `No price data available for mint ${mint}.` }],
          isError: true
        };
      }
      const payload = { mint, priceUsd: Number(entry.price), type: entry.type };
      return {
        content: [{ type: "text", text: JSON.stringify(payload, null, 2) }],
        structuredContent: payload
      };
    } catch (e) {
      return {
        content: [{ type: "text", text: `Failed to fetch token price: ${String(e.message ?? e)}` }],
        isError: true
      };
    }
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "tcd-terminal-mcp",
  title: "TCD Terminal MCP",
  version: "0.1.0",
  instructions: "Read-only market intelligence tools from TCD Terminal. Use `get_solana_network_stats` for live epoch/slot/TPS, `get_protocol_revenue` for top Solana protocols by 24h revenue and fees, and `get_token_price` for the current USD price of any SPL token by mint address.",
  tools: [get_solana_network_stats_default, get_protocol_revenue_default, get_token_price_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
